
from ..pitch import NotePitch


C_DOUBLE_FLAT_0 = NotePitch('C', 'bb' , 0)
D_DOUBLE_FLAT_0 = NotePitch('D', 'bb' , 0)
E_DOUBLE_FLAT_0 = NotePitch('E', 'bb' , 0)
F_DOUBLE_FLAT_0 = NotePitch('F', 'bb' , 0)
G_DOUBLE_FLAT_0 = NotePitch('G', 'bb' , 0)
A_DOUBLE_FLAT_0 = NotePitch('A', 'bb' , 0)
B_DOUBLE_FLAT_0 = NotePitch('B', 'bb' , 0)

C_DOUBLE_FLAT_1 = NotePitch('C', 'bb' , 1)
D_DOUBLE_FLAT_1 = NotePitch('D', 'bb' , 1)
E_DOUBLE_FLAT_1 = NotePitch('E', 'bb' , 1)
F_DOUBLE_FLAT_1 = NotePitch('F', 'bb' , 1)
G_DOUBLE_FLAT_1 = NotePitch('G', 'bb' , 1)
A_DOUBLE_FLAT_1 = NotePitch('A', 'bb' , 1)
B_DOUBLE_FLAT_1 = NotePitch('B', 'bb' , 1)

C_DOUBLE_FLAT_2 = NotePitch('C', 'bb' , 2)
D_DOUBLE_FLAT_2 = NotePitch('D', 'bb' , 2)
E_DOUBLE_FLAT_2 = NotePitch('E', 'bb' , 2)
F_DOUBLE_FLAT_2 = NotePitch('F', 'bb' , 2)
G_DOUBLE_FLAT_2 = NotePitch('G', 'bb' , 2)
A_DOUBLE_FLAT_2 = NotePitch('A', 'bb' , 2)
B_DOUBLE_FLAT_2 = NotePitch('B', 'bb' , 2)

C_DOUBLE_FLAT_3 = NotePitch('C', 'bb' , 3)
D_DOUBLE_FLAT_3 = NotePitch('D', 'bb' , 3)
E_DOUBLE_FLAT_3 = NotePitch('E', 'bb' , 3)
F_DOUBLE_FLAT_3 = NotePitch('F', 'bb' , 3)
G_DOUBLE_FLAT_3 = NotePitch('G', 'bb' , 3)
A_DOUBLE_FLAT_3 = NotePitch('A', 'bb' , 3)
B_DOUBLE_FLAT_3 = NotePitch('B', 'bb' , 3)

C_DOUBLE_FLAT_4 = NotePitch('C', 'bb' , 4)
D_DOUBLE_FLAT_4 = NotePitch('D', 'bb' , 4)
E_DOUBLE_FLAT_4 = NotePitch('E', 'bb' , 4)
F_DOUBLE_FLAT_4 = NotePitch('F', 'bb' , 4)
G_DOUBLE_FLAT_4 = NotePitch('G', 'bb' , 4)
A_DOUBLE_FLAT_4 = NotePitch('A', 'bb' , 4)
B_DOUBLE_FLAT_4 = NotePitch('B', 'bb' , 4)

C_DOUBLE_FLAT_5 = NotePitch('C', 'bb' , 5)
D_DOUBLE_FLAT_5 = NotePitch('D', 'bb' , 5)
E_DOUBLE_FLAT_5 = NotePitch('E', 'bb' , 5)
F_DOUBLE_FLAT_5 = NotePitch('F', 'bb' , 5)
G_DOUBLE_FLAT_5 = NotePitch('G', 'bb' , 5)
A_DOUBLE_FLAT_5 = NotePitch('A', 'bb' , 5)
B_DOUBLE_FLAT_5 = NotePitch('B', 'bb' , 5)

C_DOUBLE_FLAT_6 = NotePitch('C', 'bb' , 6)
D_DOUBLE_FLAT_6 = NotePitch('D', 'bb' , 6)
E_DOUBLE_FLAT_6 = NotePitch('E', 'bb' , 6)
F_DOUBLE_FLAT_6 = NotePitch('F', 'bb' , 6)
G_DOUBLE_FLAT_6 = NotePitch('G', 'bb' , 6)
A_DOUBLE_FLAT_6 = NotePitch('A', 'bb' , 6)
B_DOUBLE_FLAT_6 = NotePitch('B', 'bb' , 6)

C_DOUBLE_FLAT_7 = NotePitch('C', 'bb' , 7)
D_DOUBLE_FLAT_7 = NotePitch('D', 'bb' , 7)
E_DOUBLE_FLAT_7 = NotePitch('E', 'bb' , 7)
F_DOUBLE_FLAT_7 = NotePitch('F', 'bb' , 7)
G_DOUBLE_FLAT_7 = NotePitch('G', 'bb' , 7)
A_DOUBLE_FLAT_7 = NotePitch('A', 'bb' , 7)
B_DOUBLE_FLAT_7 = NotePitch('B', 'bb' , 7)

C_DOUBLE_FLAT_8 = NotePitch('C', 'bb' , 8)
D_DOUBLE_FLAT_8 = NotePitch('D', 'bb' , 8)
E_DOUBLE_FLAT_8 = NotePitch('E', 'bb' , 8)
F_DOUBLE_FLAT_8 = NotePitch('F', 'bb' , 8)
G_DOUBLE_FLAT_8 = NotePitch('G', 'bb' , 8)
A_DOUBLE_FLAT_8 = NotePitch('A', 'bb' , 8)
B_DOUBLE_FLAT_8 = NotePitch('B', 'bb' , 8)

C_DOUBLE_FLAT_9 = NotePitch('C', 'bb' , 9)
D_DOUBLE_FLAT_9 = NotePitch('D', 'bb' , 9)
E_DOUBLE_FLAT_9 = NotePitch('E', 'bb' , 9)
F_DOUBLE_FLAT_9 = NotePitch('F', 'bb' , 9)
G_DOUBLE_FLAT_9 = NotePitch('G', 'bb' , 9)
A_DOUBLE_FLAT_9 = NotePitch('A', 'bb' , 9)
B_DOUBLE_FLAT_9 = NotePitch('B', 'bb' , 9)
