
from ..pitch import NotePitch


C_FLAT_0 = NotePitch('C', 'b' , 0)
D_FLAT_0 = NotePitch('D', 'b' , 0)
E_FLAT_0 = NotePitch('E', 'b' , 0)
F_FLAT_0 = NotePitch('F', 'b' , 0)
G_FLAT_0 = NotePitch('G', 'b' , 0)
A_FLAT_0 = NotePitch('A', 'b' , 0)
B_FLAT_0 = NotePitch('B', 'b' , 0)

C_FLAT_1 = NotePitch('C', 'b' , 1)
D_FLAT_1 = NotePitch('D', 'b' , 1)
E_FLAT_1 = NotePitch('E', 'b' , 1)
F_FLAT_1 = NotePitch('F', 'b' , 1)
G_FLAT_1 = NotePitch('G', 'b' , 1)
A_FLAT_1 = NotePitch('A', 'b' , 1)
B_FLAT_1 = NotePitch('B', 'b' , 1)

C_FLAT_2 = NotePitch('C', 'b' , 2)
D_FLAT_2 = NotePitch('D', 'b' , 2)
E_FLAT_2 = NotePitch('E', 'b' , 2)
F_FLAT_2 = NotePitch('F', 'b' , 2)
G_FLAT_2 = NotePitch('G', 'b' , 2)
A_FLAT_2 = NotePitch('A', 'b' , 2)
B_FLAT_2 = NotePitch('B', 'b' , 2)

C_FLAT_3 = NotePitch('C', 'b' , 3)
D_FLAT_3 = NotePitch('D', 'b' , 3)
E_FLAT_3 = NotePitch('E', 'b' , 3)
F_FLAT_3 = NotePitch('F', 'b' , 3)
G_FLAT_3 = NotePitch('G', 'b' , 3)
A_FLAT_3 = NotePitch('A', 'b' , 3)
B_FLAT_3 = NotePitch('B', 'b' , 3)

C_FLAT_4 = NotePitch('C', 'b' , 4)
D_FLAT_4 = NotePitch('D', 'b' , 4)
E_FLAT_4 = NotePitch('E', 'b' , 4)
F_FLAT_4 = NotePitch('F', 'b' , 4)
G_FLAT_4 = NotePitch('G', 'b' , 4)
A_FLAT_4 = NotePitch('A', 'b' , 4)
B_FLAT_4 = NotePitch('B', 'b' , 4)

C_FLAT_5 = NotePitch('C', 'b' , 5)
D_FLAT_5 = NotePitch('D', 'b' , 5)
E_FLAT_5 = NotePitch('E', 'b' , 5)
F_FLAT_5 = NotePitch('F', 'b' , 5)
G_FLAT_5 = NotePitch('G', 'b' , 5)
A_FLAT_5 = NotePitch('A', 'b' , 5)
B_FLAT_5 = NotePitch('B', 'b' , 5)

C_FLAT_6 = NotePitch('C', 'b' , 6)
D_FLAT_6 = NotePitch('D', 'b' , 6)
E_FLAT_6 = NotePitch('E', 'b' , 6)
F_FLAT_6 = NotePitch('F', 'b' , 6)
G_FLAT_6 = NotePitch('G', 'b' , 6)
A_FLAT_6 = NotePitch('A', 'b' , 6)
B_FLAT_6 = NotePitch('B', 'b' , 6)

C_FLAT_7 = NotePitch('C', 'b' , 7)
D_FLAT_7 = NotePitch('D', 'b' , 7)
E_FLAT_7 = NotePitch('E', 'b' , 7)
F_FLAT_7 = NotePitch('F', 'b' , 7)
G_FLAT_7 = NotePitch('G', 'b' , 7)
A_FLAT_7 = NotePitch('A', 'b' , 7)
B_FLAT_7 = NotePitch('B', 'b' , 7)

C_FLAT_8 = NotePitch('C', 'b' , 8)
D_FLAT_8 = NotePitch('D', 'b' , 8)
E_FLAT_8 = NotePitch('E', 'b' , 8)
F_FLAT_8 = NotePitch('F', 'b' , 8)
G_FLAT_8 = NotePitch('G', 'b' , 8)
A_FLAT_8 = NotePitch('A', 'b' , 8)
B_FLAT_8 = NotePitch('B', 'b' , 8)

C_FLAT_9 = NotePitch('C', 'b' , 9)
D_FLAT_9 = NotePitch('D', 'b' , 9)
E_FLAT_9 = NotePitch('E', 'b' , 9)
F_FLAT_9 = NotePitch('F', 'b' , 9)
G_FLAT_9 = NotePitch('G', 'b' , 9)
A_FLAT_9 = NotePitch('A', 'b' , 9)
B_FLAT_9 = NotePitch('B', 'b' , 9)

