
from ..pitch import NotePitch


C_0 = NotePitch('C', '' , 0)
D_0 = NotePitch('D', '' , 0)
E_0 = NotePitch('E', '' , 0)
F_0 = NotePitch('F', '' , 0)
G_0 = NotePitch('G', '' , 0)
A_0 = NotePitch('A', '' , 0)
B_0 = NotePitch('B', '' , 0)

C_1 = NotePitch('C', '' , 1)
D_1 = NotePitch('D', '' , 1)
E_1 = NotePitch('E', '' , 1)
F_1 = NotePitch('F', '' , 1)
G_1 = NotePitch('G', '' , 1)
A_1 = NotePitch('A', '' , 1)
B_1 = NotePitch('B', '' , 1)

C_2 = NotePitch('C', '' , 2)
D_2 = NotePitch('D', '' , 2)
E_2 = NotePitch('E', '' , 2)
F_2 = NotePitch('F', '' , 2)
G_2 = NotePitch('G', '' , 2)
A_2 = NotePitch('A', '' , 2)
B_2 = NotePitch('B', '' , 2)

C_3 = NotePitch('C', '' , 3)
D_3 = NotePitch('D', '' , 3)
E_3 = NotePitch('E', '' , 3)
F_3 = NotePitch('F', '' , 3)
G_3 = NotePitch('G', '' , 3)
A_3 = NotePitch('A', '' , 3)
B_3 = NotePitch('B', '' , 3)

C_4 = NotePitch('C', '' , 4)
D_4 = NotePitch('D', '' , 4)
E_4 = NotePitch('E', '' , 4)
F_4 = NotePitch('F', '' , 4)
G_4 = NotePitch('G', '' , 4)
A_4 = NotePitch('A', '' , 4)
B_4 = NotePitch('B', '' , 4)

C_5 = NotePitch('C', '' , 5)
D_5 = NotePitch('D', '' , 5)
E_5 = NotePitch('E', '' , 5)
F_5 = NotePitch('F', '' , 5)
G_5 = NotePitch('G', '' , 5)
A_5 = NotePitch('A', '' , 5)
B_5 = NotePitch('B', '' , 5)

C_6 = NotePitch('C', '' , 6)
D_6 = NotePitch('D', '' , 6)
E_6 = NotePitch('E', '' , 6)
F_6 = NotePitch('F', '' , 6)
G_6 = NotePitch('G', '' , 6)
A_6 = NotePitch('A', '' , 6)
B_6 = NotePitch('B', '' , 6)

C_7 = NotePitch('C', '' , 7)
D_7 = NotePitch('D', '' , 7)
E_7 = NotePitch('E', '' , 7)
F_7 = NotePitch('F', '' , 7)
G_7 = NotePitch('G', '' , 7)
A_7 = NotePitch('A', '' , 7)
B_7 = NotePitch('B', '' , 7)

C_8 = NotePitch('C', '' , 8)
D_8 = NotePitch('D', '' , 8)
E_8 = NotePitch('E', '' , 8)
F_8 = NotePitch('F', '' , 8)
G_8 = NotePitch('G', '' , 8)
A_8 = NotePitch('A', '' , 8)
B_8 = NotePitch('B', '' , 8)

C_9 = NotePitch('C', '' , 9)
D_9 = NotePitch('D', '' , 9)
E_9 = NotePitch('E', '' , 9)
F_9 = NotePitch('F', '' , 9)
G_9 = NotePitch('G', '' , 9)
A_9 = NotePitch('A', '' , 9)
B_9 = NotePitch('B', '' , 9)
